#!/bin/sh
table_data="staff_date_done.txt"
if [ -f ${table_data} ];then
   echo "${table_data} exist"
   old_encoding=$(file -b --mime-encoding ${table_data})
   echo ${old_encoding}
   iconv -f $old_encoding -t utf-8 ${table_data}>staff_date_done_utf8.txt
   #判断转码是否成功
   if [ $? -ne 0 ];then
      echo "change fail"
      exit
   else
      echo "change success"
      mysql -ukqx test -e "load data local infile '/home/CC/staff_date_done_utf8.txt' into table cache_staff_date_done character set utf8 ignore 1 lines;"
      #判断加载文件是否成功
      if [ $? -ne 0 ];then
         echo "load fail"
         exit
      else
         echo "load success"
         rm -rf staff_date_done_utf8.txt
         exit
      fi
   fi
else
   echo "${table_data} not exist"
   exit
fi
